baseURL = "https://arise-project.github.io/"
languageCode = "uk-ua"
title = "Логістична компанія «ЮТА»"
theme = "arcana"
copyright = "© UTAGBK. All rights reserved"

[taxonomies]
    tag = "tags"

[params]
    description = "A business/corporate style responsive site template."
    show_post_dates = false

    [[params.social]]
        title = "Twitter"
        icon = "fa-twitter"
        url = "#"
    [[params.social]]
        title = "Facebook"
        icon = "fa-facebook-f"
        url = "#"
    [[params.social]]
        title = "LinkedIn"
        icon = "fa-linkedin-in"
        url = "#"

    [params.footer]

        [[params.footer.links]]
            header = "Наші контакти"
        [[params.footer.links.links]]
            title = "Відділ продажів:"
            url = "tel:0 800 300 577"
        [[params.footer.links.links]]
            title = "0 800 300 577"
            url = "tel:0 800 300 577"
        [[params.footer.links.links]]
            title = "Електронна адреса:"
            url = "mail:sales@UTAGBK.com.ua"
        [[params.footer.links.links]]
            title = "sales@UTAGBK.com.ua"
            url = "sales@UTAGBK.com.ua"
        [[params.footer.links.links]]
            title = "Головний офіс:"
            url = "#"
        [[params.footer.links.links]]
            title = "м. Київ, вул. Інститутська, 19Б, оф. 35"
            url = "#"
        [[params.footer.links.links]]
            title = "Одеський офіс:"
            url = "#"
        [[params.footer.links.links]]
            title = "м. Одеса, вул. Генуезька 24-Б, оф. 616"
            url = "#"

        [params.footer.contact_form]
            enabled = true
            header = "Зворотнiй зв'язок"
            action = ""