[[main]]
    name = "Транспорт"
    weight = 27
[[main]]
    parent = "Транспорт"
    name = "ЗАЛІЗНИЧНІ ПЕРЕВЕЗЕННЯ"
    weight = 28
    url = "/_train"
[[main]]
    parent = "Транспорт"
    name = "АВТОМОБІЛЬНІ ПЕРЕВЕЗЕННЯ"
    weight = 29
    url = "/_truck"

[[main]]
    name = "Услуги"
    weight = 30
[[main]]
    parent = "Услуги"
    name = "Таможенное оформление"
    weight = 31
    url = "/"
[[main]]
    parent = "Услуги"
    name = "Складская логистика"
    weight = 32
    url = "/"
[[main]]
    parent = "Услуги"
    name = "Консалтинг"
    weight = 33
    url = "/"

[[main]]
    name = "Сферы"
    weight = 34
[[main]]
    parent = "Сферы"
    name = "Металлургия"
    weight = 35
    url = "/"
[[main]]
    parent = "Сферы"
    name = "Строительство"
    weight = 36
    url = "/"
[[main]]
    parent = "Сферы"
    name = "Бытовая техника"
    weight = 37
    url = "/"

[[main]]
    name = "Компания"
    weight = 38
    url="/_company/"

[[main]]
    name = "Контакты"
    weight = 39
    url = "/"